---
title: "Homework 3"
author: "Group 1"
date: ''
output:
  pdf_document:
    includes:
      in_header: header.tex
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
---

\begin{center}
\bigskip
\bigskip
\bigskip
Prepared for:\\
\medskip
Dr. Nathan Bastian\\
\smallskip
City University of New York, School of Professional Studies - Data 621\\
\bigskip
Prepared by:\\
\medskip
Group 1\\ 
\medskip
Senthil Dhanapal\\ 
\smallskip
Yadu Chittampalli\\
\smallskip
Christophe Hunt\\  

\end{center}

```{r, include = FALSE}
library(pacman)
p_load(Hmisc, xlsx, xtable, knitr, scales, magrittr, tidyr, plyr, dplyr, 
       stringr, e1071, corrplot, knitcitations, bibtex, missForest,
       foreach, doParallel, stargazer, forecast)
```

```{r, include=FALSE, cache=TRUE}
download.file("https://github.com/ChristopheHunt/DATA-621-Group-1/raw/master/Homework%203/Data%20Dictionary.xlsx?raw=true", destfile = "Data Dictionary HW3 - Group 1.xlsx", mode = 'wb')
daDict <- read.xlsx("Data Dictionary HW3 - Group 1.xlsx", sheetIndex = 1)
file.remove(dir(getwd(), pattern = "Data Dictionary HW3 - Group 1", full.names = TRUE))
```
\newpage

# Introduction

# Statement of the Problem

# Data Exploration  

```{r programming style guide, echo=FALSE, eval=FALSE}
##Style guide
##USE CAMEL CASING!! https://en.wikipedia.org/wiki/Camel_case, start with lowercase then each word after start with upper case
##upper case for vector, lists, etc. ex. X <- c("yes","no","true","false")
##lower case for scalar/single value, ex. x <- 1
##data frame start with df followed by description, ex. dfEval <- evaluation data frame
##assignments use "<-" not "="
```

```{r, echo=FALSE, results='asis', cache=TRUE}
dfTr <- read.csv("https://raw.githubusercontent.com/ChristopheHunt/DATA-621-Group-1/master/Homework%203/crime-training-data.csv")
  
#colnames(dfTr) <- mapvalues(as.vector(colnames(dfTr)), from = str_trim(data_dictionary$VARIABLE.NAME), to = as.vector(str_trim(data_dictionary$DEFINITION)))

digits <- c(1) 

descriptive <- describe( dfTr %>% select(-target) # TODO figure out why rad has a wierd frequency table
                        , descript = "Table 1 : Descriptive Statistics", digits = digits)
latex(descriptive, file = '')
```

```{r, eval=FALSE, echo = FALSE}
#TODO figure out why this is not working anymore 
for (i in seq(1:length(descriptive))){ 
                     for (j in c(6,9,12)){names(descriptive[[i]]$counts)[j] <- paste0(names(descriptive[[i]]$counts)[j]," freq")
                                         }
     descriptive[[i]]$counts <- (descriptive[[i]]$counts[-c(4,7,8:10,11)])
     
     descriptive[[i]]$counts[7] <- round(sapply(dfTr[i + 1], function(x) median(x, na.rm = TRUE)), digits = digits)
     names(descriptive[[i]]$counts)[7] <- "Median"
     
     descriptive[[i]]$counts[8] <- round(sapply(dfTr[i + 1], function(x) sd(x, na.rm = TRUE)), digits = digits)
     names(descriptive[[i]]$counts)[8] <- "SD"
     
     descriptive[[i]]$counts[9] <- round(sapply(dfTr[i + 1], function(x) skewness(x, na.rm = TRUE)), digits = digits)
     names(descriptive[[i]]$counts)[9] <- "Skew"
     
     descriptive[[i]]$counts <- (descriptive[[i]]$counts[c(1:4,7:9,5:6)]) #reorder 
}
```

```{r, fig.cap= "Correlation Plot of Training Data Set", echo = FALSE, cache=TRUE}
dfTrMx <- as.matrix(dfTr)
corMx <- cor(dfTrMx , use = "everything",  method = c("pearson"))
corrplot(corMx, order = "hclust", addrect = 2, method = "square", tl.col = "black", tl.cex = .5, na.label = " ")
```
