---
title: "Untitled"
author: "Yadu"
date: "November 5, 2016"
output: html_document
---

```{r}
library(stringr)
library(dplyr)
imputedDfTr <- read.csv("https://raw.githubusercontent.com/ChristopheHunt/DATA-621-Group-1/master/Homework%204/imputed_insurance_training_data.csv")
imputedDfTr <- subset(imputedDfTr, select = -INDEX)
```

```{r}
removedollars <- function(column){
             as.numeric(gsub("\\,","",gsub("\\$","", column)))
}
```

```{r}
imputedDfTr <- imputedDfTr %>%
        mutate(INCOME = removedollars(INCOME),
               HOME_VAL = removedollars(HOME_VAL),
               BLUEBOOK = removedollars(BLUEBOOK),
               OLDCLAIM = removedollars(OLDCLAIM),
               MSTATUS = gsub("z_", "", MSTATUS),
               URBANICITY = gsub("z_", "", URBANICITY),
               EDUCATION = gsub("z_", "", EDUCATION),
               EDUCATION = gsub("<", "Less Than ", EDUCATION),
               JOB = gsub("z_", "", JOB),
               CAR_TYPE = gsub("z_", "", CAR_TYPE),
               SEX = gsub("z_", "", SEX))
```

```{r}
winsorize <- function(x, multiple=2.2)
{
  q <- quantile(x)
  iqr <- IQR(x)
  iqrAdjusted <- iqr*multiple

  rangeLow <- q['25%']-iqrAdjusted
  rangeHigh <- q['75%']+iqrAdjusted

  x[x<rangeLow] <- min(x[x>rangeLow])
  x[x>rangeHigh] <- max(x[x<rangeHigh])

  return(x)  

}
library(forecast)

winsorizedDataset <- function(dataset){
  dataset <- dataset[,1:ncol(dataset)]
  wdataset <- matrix(data = 0, nrow = nrow(dataset), ncol = ncol(dataset))
  #l1 <- numeric(ncol(dataset))
  for (i in 1:ncol(dataset)){
    if(i == 1 || i == 2 || i == 3 || i == 5 || i == 8 || i == 10 || i == 11 || i == 12 || i == 13 || i == 15 || i == 18 || i == 19 || i == 21 || i == 22 || i == 23 || i == ncol(dataset)){
      wdataset[,i] <- dataset[,i]
    }
    else {
    wdataset[,i] <- winsorize(dataset[,i], multiple = 2.2)
    wdataset[,i] <- as.numeric(wdataset[,i])
    #l1[i] <- BoxCox.lambda(wdataset[,i])
    }
    colnames(wdataset) <- colnames(dataset)
  }
  return(data.frame(wdataset))
}
#lambdas <- winsorizedandtransformed(crimes)[[2]]
#wtcrimes <- winsorizedandtransformed(crimes)[[1]]
wimputedDfTr <- winsorizedDataset(imputedDfTr)
#library(stargazer)
#stargazer(wimputedDfTr, header = FALSE)
```

```{r}
library(car)
fit <- lm(TARGET_AMT ~ KIDSDRIV + AGE + HOMEKIDS + YOJ + INCOME + PARENT1 + HOME_VAL + MSTATUS + SEX + EDUCATION + JOB + TRAVTIME + CAR_USE + BLUEBOOK + TIF + CAR_TYPE + RED_CAR + OLDCLAIM + CLM_FREQ + REVOKED + MVR_PTS + CAR_AGE + URBANICITY, data=dfTr)
ncvTest(fit, ~ KIDSDRIV + AGE + HOMEKIDS + YOJ + INCOME + PARENT1 + HOME_VAL + MSTATUS + SEX + EDUCATION + JOB + TRAVTIME + CAR_USE + BLUEBOOK + TIF + CAR_TYPE + RED_CAR + OLDCLAIM + CLM_FREQ + REVOKED + MVR_PTS + CAR_AGE + URBANICITY, data=dfTr)
```

```{r}
residualPlots(fit)
```

```{r}
l1 = BoxCox.lambda(as.numeric(wimputedDfTr$INCOME))
l2 = BoxCox.lambda(as.numeric(wimputedDfTr$HOME_VAL))
l3 = BoxCox.lambda(as.numeric(wimputedDfTr$OLDCLAIM))
```

The Box-Cox transformations were done only on three of the input variables - income, house value, and the total number of claims during the past 5 years. These transformations were done based on the residual plots. In the residual plots, these three variables showed a great deal of non-constant variance because the plots were funnel-shaped. 