---
title: "liquors"
author: "Yadu"
date: "November 20, 2016"
output: html_document
---

According to the Distilled Spirits Council, the continuous growth of the distilled spirits industry is owed to several key factors - continuous fascination with American Whiskeys in the United States and abroad, innovations in flavors, permiumization across all spirits categories leading to consumer interest, improved regulatory and tax environment resulting in expanded market access and a relatively low number of state tax threats, and the growth of small distillers, which expanded grassroots and overall interest in the spirits category. There was a slight increase in market share vs. beer for 5 consecutive years. Distilled Spirits Council President and CEO Peter H. Cressy says, "Consumer interest in industry innovations and premium products from distilled spirits producers of all sizes contributed to another year of steady growth in 2014."   

The Council Senior Vice President for International Trade Christine LoCascio predicted that in 2014, American spirits exports would grow 3.7% to total $1.56 billion. LoCascio said, "The industry anticipates its fifth continuous year of record exports through a combination of market opening agreements, innovative marketing programs by individual companies and the spirits industry's export promotion program." 

http://www.discus.org/2014-us-market-report-distilled-spirits-industry-delivers-steady-growth/

In another study conducted in 2012 in Idaho, the monthly revenue generated was examined rather than the yearly revenue generated. The continued growth was rather owed to the number of weekends a month has (five instead of four) and to the higher prices in neighboring states. In Washington, the voters approved an initiative that led the state to sell its liquor stores and add new distributor and retail fees, making prices in the neighboring states (Idaho and Oregon) look better. There were no changes made in marketing or pricing in response to the regulatory shift in Washington.     

In 2011, Idaho lawmakers commissioned a report that found that the state could privatize liquor sales without a loss in the revenue. According to Jeff Anderson, leader of Idaho's liquor division, prices of liquor might also rise as a result of this. 

http://onesearch.cuny.edu/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=TN_gale_ofg298684527&indx=9&recIds=TN_gale_ofg298684527&recIdxs=8&elementId=8&renderMode=poppedOut&displayMode=full&frbrVersion=5&frbg=&&dscnt=0&scp.scps=scope%3A%28CUNY_BEPRESS%29%2Cscope%3A%28BB%29%2Cscope%3A%28BB_LIBGUIDES%29%2Cscope%3A%28AL%29%2Cprimo_central_multiple_fe&tb=t&mode=Basic&vid=bb&srt=rank&tab=default_tab&dum=true&vl(freeText0)=liquor%20sales&dstmp=1479655965260

The alcohol industry has various segments that may not necessarily act as one. However, all of these segments are commonly interested in normalizing and encouraging the consumption of alcohol, minimizing government checks and regulation on their ability to market, advertise, and distribute their products, minimizing taxes and law violation penalties on the sale of their products, and maximizing the focus of alcohol control laws on consumer for harm resulting from product use, distancing themselves and their products from problems inevitably associated with their use.

There are two different systems of sales that states operate under - license-to-sell system and control state system. 

The license-to-sell system is a system requiring state-issued licensure to sell alcoholic beverages. The law enforcement varies state-wise although most states maintain some state enforcement agency and allow for local enforcement agency roles. 

On the other hand, the control state system is a system where each state participates in a unique way as part of the alcohol industry, aiming to generate high levels of revenue as well as giving consideration to public health and safety concerns and obligations. Following the Prohibition era, several states would take control of many facets of alcohol sales and distribution. But due to constant pressure from the alcohol industry and from other industries demanding a share of the sales market, there has been a decline in the number of such states. 

http://www.alcoholpolicymd.com/pdf/AMA_Final_web_1.pdf

### Inventory Prediction ###

The main goal that has to be achieved in inventory prediction is increasing the efficiency without decreasing the service value offered to the customers.

When managing the levels of inventory, it is important to maintain moderate level(s) - not too high and not too low. If the inventory level is excessive, business funds can get wasted. These funds would not be able to be used for any other purpose, thus involving an opportunity cost. The costs of shortage, handling insurance, recording and inspection would proportionately increase along with inventory volume, thus impairing profitability. 

On the other hand, low level(s) of inventory may result in frequent interruptions in the production schedule resulting in under-utilization of capacity and lower sales. 

When making predictions about orders that should be placed, assumptions are made as follows - uncertainty always exists regardless of the method(s) used, new technologies cannot always be forecasted for which paradigms do not exist, and social policy will be formulated where the future would be affected, changing the accuracy of the forecast @article{title = "An Overview of Forecasting Methodology", journal = "Survival Statistics", year = "1993", doi = "http://www.statpac.org/research-library/forecasting.htm", author = "David S. Walonick, Ph.D"}. 

One useful method for predicting inventories is the extrapolation of trends. In this method, trends and cycles in the historical data are examined and mathematical techniques are used to extrapolate to the future. The model chosen for forecasting would depend on the historical data @article{title = "An Overview of Forecasting Methodology", journal = "Survival Statistics", year = "1993", doi = "http://www.statpac.org/research-library/forecasting.htm", author = "David S. Walonick, Ph.D"}. 

One of the most common models used in this method is decomposition, where historical data is separated into trend, seasonal, and random components. As a result, forecasts are produced using "turning point analysis". Other examples of models used are adaptive filtering, Box-Jenkins analysis, simple linear regression, curve fitting, and weighted smoothing @article{title = "An Overview of Forecasting Methodology", journal = "Survival Statistics", year = "1993", doi = "http://www.statpac.org/research-library/forecasting.htm", author = "David S. Walonick, Ph.D"}. 

According to Makridakis, "Judgmental forecasting is superior to mathematical models, although there are several forecasting applications where computer-generated models would be more feasible." When inventory levels for bulk-quantity items would need to be forecasted monthly by large manufacturing companies, generating models through computer software would be more efficient @article{title = "An Overview of Forecasting Methodology", journal = "Survival Statistics", year = "1993", doi = "http://www.statpac.org/research-library/forecasting.htm", author = "David S. Walonick, Ph.D"}. 

http://www.statpac.org/research-library/forecasting.htm

Forecasting the demand of a product is very essential in predicting the order quantity. As a result, a data bank is created, helping the decision makers settle targets, create plans, and demonstrate changes in the business setting. 

Two different methods are utilized in the investigation of the future demand - quantitative and qualitative. In quantitative methods, mathematical consistencies in the history are searched for. Two subcategories exist in quantitative methods - time series models and correlation models. 

On the other hand, qualitative methods are based on the opinions that people have had about the product in the past based on their experiences, premonitions, and emotions. 

However, when the most suitable forecast model gets selected, it is not necessarily based solely on quantitative or qualitative variables. The forecast model can even combine several models. 

http://www.slideshare.net/AbhishekKumar159/demand-forecast-process-and-inventory-management

In two studies that were conducted, the statistical data from the previous time interval was used to predict what would happen in the next time interval. One study was for pharmaceutical distribution companies. The other study involved data mining models @article{author = "Kumar, Abhishek", (2012), title = "Demand forecast process and inventory management", Retrieved from http://www.slideshare.net/AbhishekKumar159/demand-forecast-process-and-inventory-management} .  

In one study involving pharmaceutical distribution companies, the purpose was to propose a novel method to forecast the sales of the companies. Network-based analysis was conducted to find clique sets and group members and to use the sales data of comembers. The reason for this was the lack of sufficient historic sales records of each drug @article{Cengage Learning, Inc., title = "Intelligent sales prediction for pharmaceutical distribution companies: a data mining based approach", journal = "Mathematical Problems in Engineering", year = "2014", doi = "http://dx.doi.org.remote.baruch.cuny.edu/10.1155/2014/420310", author = "Neda Khalil Zadeh, Mohammad Mehdi Sepehri, and Hamid Farvaresh"}. 

Three methods were used to build time series models forecasting sales - ARIMA methodology, neural network, and an advanced hybrid neural network approach. The performance of the proposed method was evaluated using a real dataset provided by one of the leading pharmacy distribution companies in Iran. The results of the evaluation indicated that the proposed method can cope with the low number of past records while accurately forecasting medicine sales@article{Cengage Learning, Inc., title = "Intelligent sales prediction for pharmaceutical distribution companies: a data mining based approach", journal = "Mathematical Problems in Engineering", year = "2014", doi = "http://dx.doi.org.remote.baruch.cuny.edu/10.1155/2014/420310", author = "Neda Khalil Zadeh, Mohammad Mehdi Sepehri, and Hamid Farvaresh"}.

After exploratory analysis was done on the data, it was concluded that most medicines had different and specific characteristics and sales behavior, it was impractical to make a single prediction model for all medicines, and most sales records had nonlinear relationships@article{Cengage Learning, Inc., title = "Intelligent sales prediction for pharmaceutical distribution companies: a data mining based approach", journal = "Mathematical Problems in Engineering", year = "2014", doi = "http://dx.doi.org.remote.baruch.cuny.edu/10.1155/2014/420310", author = "Neda Khalil Zadeh, Mohammad Mehdi Sepehri, and Hamid Farvaresh"}. 

The reason why the hybrid neural network method was carried out was due to the fact that it is not acceptable to apply a fully linear or nonlinear model on sales data@article{Cengage Learning, Inc., title = "Intelligent sales prediction for pharmaceutical distribution companies: a data mining based approach", journal = "Mathematical Problems in Engineering", year = "2014", doi = "http://dx.doi.org.remote.baruch.cuny.edu/10.1155/2014/420310", author = "Neda Khalil Zadeh, Mohammad Mehdi Sepehri, and Hamid Farvaresh"}. 

The two forecast error measures that were used to evaluate and compare model performance were mean squared error and mean absoute error. The performance of the predicted data was significantly improved when the past records of comembers were used @article{Cengage Learning, Inc., title = "Intelligent sales prediction for pharmaceutical distribution companies: a data mining based approach", journal = "Mathematical Problems in Engineering", year = "2014", doi = "http://dx.doi.org.remote.baruch.cuny.edu/10.1155/2014/420310", author = "Neda Khalil Zadeh, Mohammad Mehdi Sepehri, and Hamid Farvaresh"}. 

http://onesearch.cuny.edu/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=TN_gale_ofa425455991&indx=3&recIds=TN_gale_ofa425455991&recIdxs=2&elementId=2&renderMode=poppedOut&displayMode=full&frbrVersion=2&frbg=&&dscnt=0&scp.scps=scope%3A%28CUNY_BEPRESS%29%2Cscope%3A%28BB%29%2Cscope%3A%28BB_LIBGUIDES%29%2Cscope%3A%28AL%29%2Cprimo_central_multiple_fe&tb=t&mode=Basic&vid=bb&srt=rank&tab=default_tab&dum=true&vl(freeText0)=inventory%20prediction%20sales&dstmp=1481346949259

The other study that examined prediction-based inventory optimization using data mining models, the Back propagation neural network was used for training the prediction model. The idea that gave rise to this method of inventory prediction was the idea that the demand of marketing is viewed as the foundation of inventory management @article{IEEE Conference Publications, title = "A Prediction-Based Inventory Optimization Using Data Mining Models", journal = "2014 Seventh International Joint Conference on Computational Sciences and Optimization", year = "2014", pages = "611-615", doi = "10.1109/CSO.2014.118", author = "Xiaoxiao Guo, Chang Liu, Wei Xu, Hui Yuan, Mingming Wang"}.   

On the basis of the prediction result, a simple and concise inventory policy was established. Following this, the historic sales data was used to estimate a normal distribution of demand and to calculate the inventory cost with inventory strategy @article{IEEE Conference Publications, title = "A Prediction-Based Inventory Optimization Using Data Mining Models", journal = "2014 Seventh International Joint Conference on Computational Sciences and Optimization", year = "2014", pages = "611-615", doi = "10.1109/CSO.2014.118", author = "Xiaoxiao Guo, Chang Liu, Wei Xu, Hui Yuan, Mingming Wang"}. 

Two models (Back Propagation Neural Network and Support Vector Regression) were established using three input variables (historical sales data, the frequency of searching the commodity, and the click volume of the commodity page) @article{IEEE Conference Publications, title = "A Prediction-Based Inventory Optimization Using Data Mining Models", journal = "2014 Seventh International Joint Conference on Computational Sciences and Optimization", year = "2014", pages = "611-615", doi = "10.1109/CSO.2014.118", author = "Xiaoxiao Guo, Chang Liu, Wei Xu, Hui Yuan, Mingming Wang"}.

When the back-propagation neural network method was used, there was more accuracy shown in the performance because the predicted values almost matched the actual values in the graphs @article{IEEE Conference Publications, title = "A Prediction-Based Inventory Optimization Using Data Mining Models", journal = "2014 Seventh International Joint Conference on Computational Sciences and Optimization", year = "2014", pages = "611-615", doi = "10.1109/CSO.2014.118", author = "Xiaoxiao Guo, Chang Liu, Wei Xu, Hui Yuan, Mingming Wang"}.

The mean absolute percentage error calculated for this model is 0.06. 

http://onesearch.cuny.edu/primo_library/libweb/action/display.do?frbrVersion=2&tabs=detailsTab&ct=display&fn=search&doc=TN_ieee10.1109%2fCSO.2014.118&indx=10&recIds=TN_ieee10.1109%2fCSO.2014.118&recIdxs=9&elementId=9&renderMode=poppedOut&displayMode=full&frbrVersion=2&frbg=&&dscnt=0&scp.scps=scope%3A%28CUNY_BEPRESS%29%2Cscope%3A%28BB%29%2Cscope%3A%28BB_LIBGUIDES%29%2Cscope%3A%28AL%29%2Cprimo_central_multiple_fe&tb=t&mode=Basic&vid=bb&srt=rank&tab=default_tab&dum=true&vl(freeText0)=inventory%20prediction%20sales&dstmp=1481412549638

There was a study conducted by the Beer Industry Electronic Commerce Coalition. The purpose of this study was to highlight, explain, and create future considerations for the advancement of forecasting future beer sales and the process around how distributors and suppliers can collaborate to achieve this goal. 

Weekly forecasts can be created by supplier, brand, package, etc. for up to fifteen weeks into the future if necessary. It is important to be aware of the product trends so that specific situations can be explained to various employees of the company at any time.

https://www.nbwa.org/sites/default/files/hitting_the_mark.pdf

http://support.sas.com/resources/papers/proceedings13/157-2013.pdf