---
title: "Final Project"
author: "Group 1"
date: ''
output:
  pdf_document:
    includes:
      in_header: header.tex
    number_sections: yes
    toc: yes
    toc_depth: 2
  html_document:
    toc: yes
    toc_depth: '2'
---

# Abstract: use 250 words or less to summarize your problem, methodology, and major outcomes (might need to wait to complete the major outcomes portion). 

#### Problem = our problem is to create a statiscal model for the number of bottle sold. This will help us predict inventory and if we were a wholesale distributor we could adjust our inventory. 

# Key words: select a few key words (up to five) related to your work.

# Introduction: describe the background and motivation of your problem.

# Literature review: discuss how other researchers have addressed similar problems, what their achievements are, and what the advantage and drawbacks of each reviewed approach are. Explain how your investigation is similar or different to the state-of-the-art. Please do not discuss paper one at a time, instead, identify key characteristics of your topic, and discuss them in a whole. Please cite the relevant papers where appropriate.

# Methodology: discuss the key aspects of your problem, data set and regression model(s). Given that you
are working on real-world data, explain at a high-level your exploratory data analysis, how you prepared
the data for regression modeling, your process for building regression models, and your model selection.

# Experimentation and Results: describe the specifics of what you did (data exploration, data preparation,
model building, model selection, model evaluation, etc.), and what you found out (statistical analyses,
interpretation and discussion of the results, etc.).

# Discussion and Conclusions: conclude your findings, limitations, and suggest areas for future work.

# References: be sure to cite all references used in the report (APA format).

# Appendices:
## Supplemental tables and/or figures.
## R statistical programming code.

https://data.iowa.gov/Economy/Iowa-Liquor-Sales/m3tr-qhgy/data