---
title: Regional Liquor Sales in Iowa
author:
  - name: Christophe Hunt
    email: christophe.hunt@spsmail.cuny.edu
    affiliation: CUNY School of Professional Studies
    footnote: Author
  - name: Senthil Dhanapal
    email: senthil.dhanapal@spsmail.cuny.edu
    affiliation: CUNY School of Professional Studies
  - name: Yadu Chittampalli
    email: yadu.chittampalli@spsmail.cuny.edu
    affiliation: CUNY School of Professional Studies
address:
  - code: CUNY School of Professional Studies
    address: CUNY School of Professional Studies, Data Analytics, New York, NY
abstract: |
  This is the abstract.

  It consists of two paragraphs
  
  #Keywords: *Liquor, Liquor Sales.*

bibliography: mybibfile.bib
output: rticles::elsevier_article
---

Problem
=================

Liquor sales are highly variable and the objective of this report is to create a statiscal model for the number of bottle sold by regional. This will help us predict inventory and assist wholesale distributors and the State of Iowa adjust inventory projections accordingly. 


Introduction
=================
describe the background and motivation of your problem.


Research Background (Literature Review)
=================


Methodology
================

discuss the key aspects of your problem, data set and regression model(s). Given that you
are working on real-world data, explain at a high-level your exploratory data analysis, how you prepared
the data for regression modeling, your process for building regression models, and your model selection.

Experimentation and Results
==========================

describe the specifics of what you did (data exploration, data preparation,
model building, model selection, model evaluation, etc.), and what you found out (statistical analyses,
interpretation and discussion of the results, etc.).

Discussion and Conclusions
==========================
conclude your findings, limitations, and suggest areas for future work.



References {#references .unnumbered}
==========

Appendices
=============

## Supplemental tables and/or figures.

# Session Info

```{r, results='asis', echo=FALSE, eval = TRUE}
toLatex(sessionInfo())
```

## R statistical programming code.

## R source code

Please see [Final Project.rmd](https://github.com/ChristopheHunt/DATA-621-Group-1/blob/master/Homework%205/Homework%205.Rmd) on GitHub for source code.   

https://github.com/ChristopheHunt/DATA-621-Group-1/blob/master/Homework%205/Homework%205.Rmd